### ISSUE TITLE
BOM encoding issue

### ISSUE THREAD

**Issue by Xunius** [MrTango/rispy#13]
Hi,
I noticed an error when trying to parse an ris file exported from EndNote. EndNote is an Mac installation in case that makes a difference. RISparser then gives the error:

```
OSError: Expected start tag in line 0:
```
It turns out that the first line of the ris file is `'\ufeffTY  - JOUR\n'` so it is not recognized as a proper tag. I saw in `parser.readris()` that there is already an effort for correcting BOM related issue, but I guess this is another case needs to be covered. Reading this [stackoverflow answer](https://stackoverflow.com/a/17912811/2005415), my guess is the file was encoded using utf-8-sig, but when reading into python it defaults to a utf-8 encoding, thus giving this error.

May be make one additional check for `st[0] == '\ufeff'`?

**Comment by shapiromatron** [comment]
Can you load a file or a link to a file w/ the BOM issue?  Then we can write some tests to it.

**Comment by shapiromatron** [comment]
@Xunius, bump :). Would you mind sending a file or adding a unit test so we can fix?

**Comment by Xunius** [comment]
Hi @shapiromatron, my old test file is long gone, and I don't have a Mac machine nor an Endnote installation. But I managed to craft one such file whose 1st character is `\ufeff`. See below:

[test.txt](https://github.com/MrTango/RISparser/files/4301271/test.txt)

I just saved the text file using the `utf-8-with-signature-mac` encoding using Emacs. Then reading that in in python:
```
fin=open('test.txt', 'r')
line=fin.readline()
print(a[0])
```

**Comment by holub008** [comment]
This bug in present in RISParser v0.4.3 & rispy v0.5.0; the bug is the same in both, so I'll address only the latter.

The check for a leading BOM is done [here](https://github.com/MrTango/rispy/blob/master/rispy/parser.py#L204). `rispy`'s `load` method asks for a `TextIO` file handle.`TextIO`'s `read` methods return `str`, and the BOM is a single character. So the check of `(c[0], c[1], c[2]) == ("\xef", "\xbb", "\xbf")` should actually just be `c[0] == '\ufeff'`. If it was anticipated that the elements of `c` were `bytes` (which doesn't make sense for a `TextIO` file object), then indexing `c` would give `int`s instead of `str`s, hence this check failing.

Another thing to note - `rispy.loads` does nothing to address a leading BOM. I think that's a reasonable choice, but wanted to check it was expected behavior.

If maintainers would like, I can fix and add a test case.

**Comment by shapiromatron** [comment]
Thanks for the report @holub008! Yes, please add a test case and submit a PR, including changes as necessary to handle the BOM as you see best. Thanks!

**Comment by shapiromatron** [comment]
Alsop @holub008, if `json.loads` could address a leading BOM, that seems like desired behavior, no need to send a user down a stack overflow rabbit hole if it's something we could easily fix.  Let me know if you think that seems to magic, but it seems appropriate to me that it could be handle from a string as well as a file-like object.

**Comment by holub008** [comment]
I'll move the check to `loads` so that all parsing entry points remove any BOM.

I think how we handle this is dependent on the target user base. A vast majority of the time, a BOM will only be present due to user error (incorrectly decoded file), so it's not like `rispy` _has_ to clean it up for them. But:

1. Many big literature databases (e.g. Pubmed, Embase) spit back non-UTF8 encoded files, which will differ from typical system defaults. Most developers don't think about encodings (or don't want to, as you point out).
2. I can't imagine a scenario in which a user would actually want to force through a BOM.

Given both of these, I'm OK with some magic!
